#!/bin/bash -e

# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>. For any questions
# about this software or licensing, please email opensource@seagate.com or
# cortx-questions@seagate.com.

# Stop the script if any command fails
set -e -u -o pipefail
BASE_DIR=$(dirname $0)
source $BASE_DIR/constants.sh

TEST_DIR=/opt/seagate/$PRODUCT_FAMILY/sspl/sspl_test

plan=${1:-}
avoid_rmq=${2:-}

if rpm -qa | grep -q sspl-test ;
then
    $TEST_DIR/run_tests.sh test $plan $avoid_rmq
    exit $?
else
    echo "Please install sspl-test RPM"
    exit 1
fi
