# Globals ----------------------------------------------------------------- {{{1
#

variables:
  GIT_DEPTH: 1  # clone only the current commit
  GIT_STRATEGY: clone  # make a fresh `git clone` of the repo for every new CI job
  GIT_SUBMODULE_STRATEGY: normal  # init and check out submodules
  CENTOS_RELEASE: cortx
  M0_VG_NO_SYMLINKS: 'true'
  WORKSPACE_NAME: "${CI_PROJECT_NAME}${CI_PIPELINE_ID}"
  WORKSPACE_DIR:  "/home/gitlab-runner/workspaces/${CI_PROJECT_NAME}${CI_PIPELINE_ID}"

stages:
  - build

before_script:
  - date -u -Isec
  - git --no-pager log -1 --pretty=fuller
  - printenv

after_script:
  - date -u -Isec


# Build ------------------------------------------------------------------- {{{1
#

build:
  stage: build
  tags: [ docker-build ]
  except: [ dev, tags ]
  script: |
    time ./jenkins/build.sh


# Docker images ----------------------------------------------------------- {{{1
#

docker:rebuild-images:
  stage: build
  tags: [ docker-image-build ]
  when: manual
  except: [ schedules ]

  variables:
    DOCKER_IMAGE_TAG: 7

  script:
    - make -C docker/ docker-image-$DOCKER_IMAGE_TAG
    - make -C docker/ push tag="${DOCKER_IMAGE_TAG}*"


docker:rebuild-images:76:
  extends: docker:rebuild-images
  variables:
    DOCKER_IMAGE_TAG: '7.6'


docker:rebuild-images:cortx:
  extends: docker:rebuild-images
  variables:
    DOCKER_IMAGE_TAG: cortx


# vim: foldmethod=marker shiftwidth=2 tabstop=2 expandtab
