COM = ('dc=com',
       {'objectclass': ['top'],
        'dc': ['com'],
        'description': ["com"]})
ORG = ('dc=seagate',
       {'objectclass': ['dcObject', 'organization'],
        'dc': ['seagate'],
        'description': ["Seagate"],
        'o': "seagate com"})
PEOPLE = ('cn=Manager',
          {'cn': ["Manager"],
           'description': ["Directory Manager"],
           'objectClass': ['organizationalRole']},
          'ou=Test',
          {'ou': 'Test',
           'description': 'Test',
           'objectclass': 'organizationalunit'},
          'ou=Cstor',
          {'ou': 'Cstor',
           'description': 'Cstor',
           'objectclass': 'organizationalunit'})
USERS1 = [('cn=victor',
           {'objectClass': ['person'],
            'cn': ['Victor'],
            'sn': ['Wallen']}),
          ('cn=sheldon',
           {'objectClass': ['person'],
            'cn': ['Sheldon'],
            'sn': ['Cooper']})]
USERS2 = [('cn=howard',
           {'objectClass': ['person'],
            'cn': ['Howard'],
            'sn': ['Wolowitz']}),
          ('cn=leonard',
           {'objectClass': ['person'],
            'cn': ['Leonard'],
            'sn': ['Hofstadter']})]
