apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: centos
  name: centos
spec:
  containers:
  - image: centos:7
    name: centosx
    command: ["/bin/sleep", "3650d"]
    securityContext:
      capabilities:
        add: ["SYS_RAWIO"]
    resources:
      limits:
        smarter-devices/sda: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}