#!/bin/sh
#
# chkconfig: 234 91 09
# description: SSPL Low Level Process
# processname: sspl-ll
#

### BEGIN INIT INFO
# Provides: sspl-ll
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: Start and stop the sspl-ll process
# Description: Create SSPL Low Level Process to handle fs events and RabbitMQ message processing
### END INIT INFO

# Source init functions
. /etc/rc.d/init.d/functions

conf_filename=/etc/sspl_ll.conf
prog_name="/opt/seagate/sspl/low-level/framework/sspl_ll_d"
prog_path="$prog_name -c $conf_filename"

start()
{
    if status "$prog_name"
    then
        echo "Process already started"
    else
        echo -n "Starting sspl-ll:"
        daemon --user root $prog_path
        rv=$?
        echo
        return $rv
    fi
}

stop ()
{
    echo -n $"Shutting down sspl-ll:"
    killproc $prog_name
    rv=$?
    echo
    return $rv
}


restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        status "$prog_name"
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
        ;;
esac
