#!/bin/bash
#
# Perform initializations prior to starting sspl_ll
#
# Create sspl-ll user and assign to groups
#
# Usage:
#    ./sspl_ll_reinit

# Add the sspl-ll user if it doesn't exist
id -u sspl-ll &>/dev/null || /usr/sbin/useradd -r -g zabbix \
    -s /sbin/nologin  \
    -c "User account to run the sspl-ll service" sspl-ll
# Assign the groups
usermod -a -G systemd-journal sspl-ll
usermod -a -G dialout sspl-ll
usermod -a -G disk sspl-ll

# Update the sudoers file with the sspl-ll user and available commands
SUDO_LINE="sspl-ll	ALL = NOPASSWD: /usr/sbin/mdadm, /usr/sbin/fwdownloader, /usr/sbin/hdparm"
grep -q "$SUDO_LINE" /etc/sudoers || echo "$SUDO_LINE" >> /etc/sudoers

# Comment out the tty requirement in sudoers file
sed -i "s/^Defaults    requiretty.*/#Defaults    requiretty/" /etc/sudoers

# Start with a clean updated drive_manager.json file and serialized dir
rm -Rf /tmp/dcs/dmreport
systemctl restart openhpid

# Grant IO abilities so that we can send ATA commands to drives as sspl-ll user
setcap cap_sys_rawio=ep /usr/bin/python2.7

# Make sure security policies are in place
cp ../files/sspl-ll_dbus_policy.rules /etc/polkit-1/rules.d
cp ../files/sspl-ll_dbus_policy.conf /etc/dbus-1/system.d


# Enable SNMP traps on the PDU to be sent to the CMU
echo "Enable SNMP traps on the PDU to be sent to the CMU"
# curl -skd '{
#      "jsonrpc": "2.0",
#      "method": "performBulk",
#      "params": {
#          "requests": [
#              // First request: Eventengine::modifyAction()
#              {"rid":"/event_engine",
# "json":{"jsonrpc":"2.0", "method":"modifyAction", "params":{"action":{"id":"SystemSnmpTrapAction", "name":"System SNMP Notification Action", "isSystem":true, "type":"SendSnmpTrap", "arguments":[{"key":"SnmpNotfType", "value":"v2Trap"},{"key":"SnmpTrapDest1", "value":"172.16.0.41:1620:public"},{"key":"SnmpTrapDest2", "value":":162:"},{"key":"SnmpTrapDest3", "value":":162:"}]}}, "id":1127}},
#              // Second request: Eventengine::modifyAction()
#              {"rid":"/event_engine",
# "json":{"jsonrpc":"2.0", "method":"modifyRule", "params":{"rule":{"id":"SystemSnmpTrapRule", "name":"System SNMP Notification Rule", "isSystem":true, "isEnabled":true, "isAutoRearm":true, "hasMatched":false, "condition":{"negate":false, "operation":0, "matchType":2, "eventId":["**"], "conditions":[]}, "actionIds":["SystemSnmpTrapAction"], "arguments":[]}}, "id":1128}}]},
#      },
#      "id": 1129
# }' https://admin:admin@172.16.1.221/bulk