#!/bin/bash
#
# Perform initializations prior to starting sspl_ll
#
# Create sspl-ll user and assign to groups
#
# Usage:
#    ./sspl_reinit <product>
#
script_dir=$(dirname $0)
# Import common constants
. $script_dir/constants.sh

[ "${1}" = "CS-L" -o "${1}" = "CS-G" ] && {
    id -u sspl-ll &>/dev/null || /usr/sbin/useradd \
        -s /sbin/nologin  \
        -c "User account to run the sspl-ll service" sspl-ll;

    # Automatically install dependencies based on config file
    sspl-ll-cli verify --checkdeps --autoinstall;
    exit;
}

chown -R sspl-ll:root /opt/seagate/$PRODUCT_FAMILY/sspl

# Create a link to low-level cli for easy global access
if [ -f /opt/seagate/$PRODUCT_FAMILY/sspl/cli/lib/sspl_ll_cli ]; then
    ln -sf /opt/seagate/$PRODUCT_FAMILY/sspl/cli/lib/sspl_ll_cli /usr/bin/sspl_ll_cli
fi

# Assign the required groups
usermod -a -G systemd-journal sspl-ll
usermod -a -G dialout sspl-ll
usermod -a -G disk sspl-ll
usermod -a -G disk sspl-ll

# Update the sudoers file with the sspl-ll user and available commands
SUDO_LINE="sspl-ll	ALL = NOPASSWD: /usr/sbin/smartctl, /usr/sbin/mdadm, /usr/bin/mount, /usr/bin/umount, /usr/sbin/swapon, /usr/sbin/swapoff, /usr/sbin/hdparm, /usr/bin/systemctl, /usr/sbin/wbcli, /usr/bin/ipmitool, /usr/bin/systemd-detect-virt, /bin/salt-call, /usr/bin/echo"
grep -q "$SUDO_LINE" /etc/sudoers || echo "$SUDO_LINE" >> /etc/sudoers

# Automatically install dependencies based on config file
# There is no --checkdeps and --autoinstall implemented in sspl-ll-cli.
#sspl-ll-cli --checkdeps --autoinstall

# Comment out the tty requirement in sudoers file
sed -i "s/^Defaults    requiretty.*/#Defaults    requiretty/" /etc/sudoers

# Start with a clean updated drive_manager.json file and serialized dir
rm -Rf /tmp/dcs/dmreport

# Grant IO abilities so that we can send ATA commands to drives as sspl-ll user
setcap cap_sys_rawio=ep /usr/bin/python2.7

# Make sure security policies are in place
cp -f /opt/seagate/$PRODUCT_FAMILY/sspl/conf/etc/polkit-1/rules.d/sspl-ll_dbus_policy.rules /etc/polkit-1/rules.d
cp -f /opt/seagate/$PRODUCT_FAMILY/sspl/conf/etc/dbus-1/system.d/sspl-ll_dbus_policy.conf /etc/dbus-1/system.d

mkdir -p /etc/sspl-ll/templates/snmp
cp -rf /opt/seagate/$PRODUCT_FAMILY/sspl/conf/snmp/* /etc/sspl-ll/templates/snmp

rm -Rf /var/run/sspl_ll
