#!/usr/bin/env bash

set -E
SCRIPT_NAME=$(basename $0)
SSPL_CONFIG_PATH="/var/sspl"

usage() {
    echo "$SCRIPT_NAME [{check|config}]"
    exit 1
}

cmd="config"
[ $# -ge 1 ] && cmd=$1

case $cmd in
    check )
        [ -f $SSPL_CONFIG_PATH/sspl-configured ]  && exit 0
        logger -i -p local3.err "SSPL is not configured."
        logger -i -p local3.err "Please run /opt/seagate/sspl/low-level/framework/sspl_init."
        exit 1
        ;;

    config )
        [ $(id -u) -ne 0 ] && echo "please run this command with root privileges" && exit 1
        rm -f $SSPL_CONFIG_PATH/sspl-configured

        # Add sspl-ll user to required groups and sudoers file etc.
        echo "Initializing SSPL configuration ... "
        /opt/seagate/sspl/low-level/framework/sspl_ll_reinit_CS_A

        # Ensure rabbitmq-server has started
        systemctl start rabbitmq-server

        # Add required user and vhost to RabbitMQ. Set user permissions etc.
        echo "Creating required RABBITMQ configuration.... "
        /opt/seagate/sspl/low-level/framework/sspl_ll_rabbitmq_reinit_CS_A
        echo "SSPL configured successfully."
        mkdir -p $SSPL_CONFIG_PATH
        touch $SSPL_CONFIG_PATH/sspl-configured
        ;;

    * )
        usage
        ;;
esac
