#!/bin/bash
#
# Perform initializations prior to starting sspl_ll
#
# Create sspl-ll user and assign to groups
#
# Usage:
#    ./sspl_ll_reinit

# Add the sspl-ll user if it doesn't exist
id -u sspl-ll &>/dev/null || /usr/sbin/useradd -r -g zabbix \
    -s /sbin/nologin  \
    -c "User account to run the sspl-ll service" sspl-ll
# Assign the groups
usermod -a -G systemd-journal sspl-ll
usermod -a -G dialout sspl-ll
usermod -a -G disk sspl-ll

# Update the sudoers file with the sspl-ll user and available commands
SUDO_LINE="sspl-ll	ALL = NOPASSWD: /usr/sbin/mdadm, /usr/sbin/wbcli, /usr/sbin/hdparm"
grep -q "$SUDO_LINE" /etc/sudoers || echo "$SUDO_LINE" >> /etc/sudoers

# Update the sudoers file with the zabbix user and available commands
SUDO_LINE="zabbix	ALL = NOPASSWD: /opt/xyratex/zabbix/collector/bin/openhpid.sh"
grep -q "$SUDO_LINE" /etc/sudoers || echo "$SUDO_LINE" >> /etc/sudoers

# Comment out the tty requirement in sudoers file
# sed -i "s/^Defaults    requiretty.*/#Defaults    requiretty/" /etc/sudoers

# Start with a clean updated drive_manager.json file and serialized dir
rm -Rf /tmp/dcs/dmreport
systemctl restart openhpid

# Grant IO abilities so that we can send ATA commands to drives as sspl-ll user
setcap cap_sys_rawio=ep /usr/bin/python2.7
